include:
  - includes/cassandra.yaml
  - includes/elasticsearch.yaml
  - includes/mongodb.yaml
  - includes/mysql.yaml
  - includes/neo4j.yaml
  - includes/oracle.yaml
  - includes/postgresql.yaml
  - includes/redis.yaml
  - includes/sql-server.yaml
services:
  study28:
    container_name: study28
    image: eeengcs/study28:1.0.0-SNAPSHOT
    depends_on:
      cassandra:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_started
      mysql:
        condition: service_started
      neo4j:
        condition: service_healthy
      oracle:
        condition: service_started
      postgresql:
        condition: service_started
      redis:
        condition: service_started
      sql-server:
        condition: service_started
    ports:
      - "8028:8028"
    networks:
      - app-net
    restart: always
networks:
  app-net:
    driver: bridge
