services:
  cassandra:
    container_name: cassandra
    image: cassandra
    volumes:
      - cassandra-node:/var/lib/cassandra:rw
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - app-net
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
volumes:
  cassandra-node:
