services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    volumes:
      - mongo-data:/data/db
      - mongo-data-config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - app-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
      - MONGODB_USERNAME=kp
      - MONGODB_PASSWORD=mikimiki
      - MONGODB_DATABASE=kp_database
    restart: always
volumes:
  mongo-data:
  mongo-data-config:
