services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
     - "3306:3306"
    networks:
      - app-net
    environment:
      - MYSQL_ROOT_PASSWORD=mikimiki
      - MYSQL_USER=kp
      - MYSQL_PASSWORD=mikimiki
      - MYSQL_DATABASE=kp_database
    restart: always
