services:
  postgresql:
    container_name: postgresql
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-net
    shm_size: 128mb
    environment:
    # - POSTGRES_USER=
      - POSTGRES_PASSWORD=secret
    restart: always
volumes:
  postgres-data:
