services:
  redis:
    container_name: redis
    image: redis
    volumes:
    - redis-data:/data
    ports:
    - "6379:6379"
    networks:
    - app-net
    restart: always
volumes:
  redis-data:
